"""Centralized visual theme for the Streamlit frontend."""

from __future__ import annotations

import streamlit as st


THEME_CSS = """
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Space+Grotesk:wght@400;500;600;700&display=swap');
:root { --ink:#08070d; --panel:rgba(20,17,31,.78); --line:rgba(194,171,255,.15); --muted:#9890ad; --white:#f5f1ff; --violet:#a77bff; --blue:#6ca9ff; --pink:#f27cff; --green:#63e6bb; }
.stApp { background:radial-gradient(circle at 12% 4%,rgba(104,49,190,.18),transparent 30%),radial-gradient(circle at 90% 16%,rgba(49,92,188,.12),transparent 28%),var(--ink); color:var(--white); font-family:'Space Grotesk',sans-serif; }
[data-testid="stHeader"] { background:transparent; }
[data-testid="stSidebar"] { background:rgba(10,8,17,.92); border-right:1px solid var(--line); }
[data-testid="stSidebarContent"] { padding:28px 18px; }
.block-container { max-width:1440px; padding:28px 46px 64px; }
.brand-mark { display:flex; gap:12px; align-items:center; color:var(--white); letter-spacing:.08em; }
.brand-mark span { color:var(--violet); font-size:25px; text-shadow:0 0 18px rgba(167,123,255,.75); }.brand-mark strong,.brand-mark small { display:block; }.brand-mark strong { font-size:12px; }.brand-mark small { color:var(--muted); font:10px 'DM Mono',monospace; margin-top:3px; }
.sidebar-rule { border-top:1px solid var(--line); margin:27px 0 23px; }.nav-caption,.card-label,.page-kicker { color:#827991; font:500 10px 'DM Mono',monospace; letter-spacing:.16em; }
[data-testid="stSidebarNav"] { display:none; }.sidebar-footer { color:#b3a9c4; font:10px 'DM Mono',monospace; letter-spacing:.08em; position:fixed; bottom:25px; }.sidebar-footer small { display:block; color:#615a70; margin:10px 0 0 15px; font-size:9px; }.status-dot { display:inline-block; width:7px; height:7px; border-radius:50%; background:var(--green); box-shadow:0 0 10px var(--green); margin-right:7px; }
[data-testid="stSidebar"] [data-testid="stRadio"] label { padding:10px 11px; color:#a79db8; border-radius:10px; margin:3px 0; }.glass-card,.empty-state,.metric-card { background:linear-gradient(135deg,rgba(35,28,54,.82),rgba(16,14,25,.9)); border:1px solid var(--line); border-radius:16px; box-shadow:0 16px 55px rgba(0,0,0,.18); }.glass-card { padding:24px; }.input-card { min-height:280px; }.card-label { display:flex; justify-content:space-between; margin-bottom:20px; }.card-label span { color:var(--green); }
h1 { font-size:clamp(34px,4.4vw,62px); letter-spacing:-.045em; line-height:1; margin:10px 0 15px; }.page-description { color:var(--muted); max-width:650px; font-size:16px; line-height:1.6; margin-bottom:32px; }.section-heading { display:flex; justify-content:space-between; border-bottom:1px solid var(--line); margin:42px 0 16px; padding-bottom:11px; color:#bcb1ce; font:11px 'DM Mono',monospace; letter-spacing:.12em; }.section-heading i { color:#676078; font-style:normal; text-transform:uppercase; letter-spacing:.06em; }
[data-testid="stTextArea"] textarea,[data-testid="stSelectbox"] div { background:rgba(8,7,13,.6)!important; color:var(--white)!important; border-color:var(--line)!important; border-radius:10px!important; }.stButton button { background:linear-gradient(100deg,#7547d7,#a35ce9); border:0; border-radius:9px; color:white; font-weight:600; box-shadow:0 0 24px rgba(130,75,224,.2); }.metric-card { min-height:125px; padding:17px; }.metric-card small,.metric-card span { display:block; font:10px 'DM Mono',monospace; color:var(--muted); letter-spacing:.1em; }.metric-card strong { display:block; font-size:30px; margin:10px 0 12px; }.metric-card span { font-size:9px; color:#665d71; }.metric-card.violet { border-top:2px solid var(--violet); }.metric-card.blue { border-top:2px solid var(--blue); }.metric-card.pink { border-top:2px solid var(--pink); }.metric-card.green { border-top:2px solid var(--green); }
.model-row { display:flex; align-items:center; gap:13px; padding:10px 0; }.model-row strong,.model-row small { display:block; }.model-row small { color:var(--muted); font-size:11px; margin-top:3px; }.model-row b { margin-left:auto; color:#5f576b; font:16px 'DM Mono',monospace; }.model-orb { width:36px; height:36px; border-radius:11px; display:grid; place-items:center; font-weight:700; }.gemini { color:#b897ff; background:rgba(135,89,230,.18); border:1px solid rgba(167,123,255,.35); }.mistral { color:#80bdff; background:rgba(71,132,219,.18); border:1px solid rgba(108,169,255,.35); }.lane-line { width:1px; height:18px; background:linear-gradient(var(--violet),var(--blue)); margin-left:18px; }.empty-state { display:flex; align-items:center; gap:17px; padding:26px; color:var(--muted); }.empty-state strong { color:var(--white); }.empty-state p { margin:6px 0 0; font-size:13px; }.empty-state.compact { padding:20px; }.empty-icon { color:var(--violet); font-size:25px; }.page-kicker { color:var(--violet); }
.pipeline-card { background:linear-gradient(135deg,rgba(35,28,54,.78),rgba(16,14,25,.9)); border:1px solid var(--line); border-radius:16px; padding:18px 22px; margin:34px 0 10px; }.pipeline-step { display:flex; align-items:center; justify-content:space-between; gap:24px; padding:9px 3px; }.pipeline-step span { color:#847a95; font:10px 'DM Mono',monospace; letter-spacing:.14em; }.pipeline-step strong { color:var(--white); font-size:15px; text-align:right; max-width:70%; overflow-wrap:anywhere; }.pipeline-arrow { color:var(--violet); font:16px 'DM Mono',monospace; opacity:.7; padding-left:4px; }.response-card { background:rgba(24,19,39,.7); border:1px solid rgba(167,123,255,.22); border-radius:14px; padding:20px 24px; color:var(--white); line-height:1.7; }.system-state { color:#b9b0c9; font:10px 'DM Mono',monospace; letter-spacing:.08em; text-align:right; padding-top:3px; }.topbar { display:flex; align-items:center; gap:18px; }.topbar-sub { color:#756c84; font:10px 'DM Mono',monospace; letter-spacing:.1em; }
.trace-stage { border:1px solid rgba(194,171,255,.12); border-left:3px solid #5c536b; border-radius:12px; background:rgba(20,17,31,.6); padding:14px 17px; margin:8px 0; }.trace-stage.recorded { border-left-color:var(--violet); }.trace-stage > div { display:flex; justify-content:space-between; align-items:center; }.trace-stage span { color:var(--white); font:11px 'DM Mono',monospace; letter-spacing:.1em; }.trace-stage small { color:var(--green); font:9px 'DM Mono',monospace; }.trace-stage.unrecorded small { color:#6d6579; }.trace-stage pre { background:rgba(8,7,13,.5); border:0; }.escalation-path { border:1px solid rgba(242,124,255,.3); border-radius:14px; padding:16px 19px; margin:24px 0; color:#e0c8ff; background:rgba(100,42,122,.16); }.escalation-path strong { color:var(--pink); font:10px 'DM Mono',monospace; letter-spacing:.12em; }.escalation-path p { margin:9px 0 0; }
@media (max-width:800px) { .block-container { padding:24px 18px 50px; } h1 { font-size:42px; }.sidebar-footer { position:static; margin-top:80px; } }
</style>
"""


def apply_theme() -> None:
	st.markdown(THEME_CSS, unsafe_allow_html=True)